import json

# Load existing content
try:
    with open('c1_content_data.json', 'r', encoding='utf-8') as f:
        content_data = json.load(f)
except FileNotFoundError:
    content_data = {"c1": {"u1": {}}}

# Unit 1 Lessons 2-8
u1_lessons = {
    "l2": {
        "words": [
            {"arabic": "مقامات", "transliteration": {"en": "Maqāmāt", "ar": "مقامات", "fr": "Maqāmāt", "de": "Maqāmāt", "ru": "макамат", "zh": "马卡马特"}, "translation": {"en": "Maqamat (rhymed prose stories)", "fr": "Maqamat", "de": "Maqamat", "ru": "Макамат", "zh": "马卡马特"}},
            {"arabic": "سجع", "transliteration": {"en": "Saj'", "ar": "سجع", "fr": "Saj'", "de": "Saj'", "ru": "садж", "zh": "萨杰"}, "translation": {"en": "Rhymed prose", "fr": "Prose rimée", "de": "Reimprosa", "ru": "Рифмованная проза", "zh": "骈文"}},
            {"arabic": "راوٍ", "transliteration": {"en": "Rāwin", "ar": "راوٍ", "fr": "Rāwin", "de": "Rāwin", "ru": "рави", "zh": "拉维"}, "translation": {"en": "Narrator", "fr": "Narrateur", "de": "Erzähler", "ru": "Рассказчик", "zh": "叙述者"}},
            {"arabic": "بطل", "transliteration": {"en": "Baṭal", "ar": "بطل", "fr": "Baṭal", "de": "Baṭal", "ru": "баталь", "zh": "巴塔尔"}, "translation": {"en": "Hero / Protagonist", "fr": "Héros", "de": "Held", "ru": "Герой", "zh": "英雄"}},
            {"arabic": "كدية", "transliteration": {"en": "Kudyah", "ar": "كدية", "fr": "Kudyah", "de": "Kudyah", "ru": "кудья", "zh": "库迪亚"}, "translation": {"en": "Mendicancy / Trickery", "fr": "Mendicité", "de": "Bettelei", "ru": "Нищенство", "zh": "技巧"}},
            {"arabic": "فصاحة", "transliteration": {"en": "Faṣāḥah", "ar": "فصاحة", "fr": "Faṣāḥah", "de": "Faṣāḥah", "ru": "фасаха", "zh": "法萨哈"}, "translation": {"en": "Eloquence", "fr": "Éloquence", "de": "Beredsamkeit", "ru": "Красноречие", "zh": "雄辩"}},
            {"arabic": "احتيال", "transliteration": {"en": "Iḥtiyāl", "ar": "احتيال", "fr": "Iḥtiyāl", "de": "Iḥtiyāl", "ru": "ихтияль", "zh": "伊赫蒂亚勒"}, "translation": {"en": "Fraud / Deceit", "fr": "Fraude", "de": "Betrug", "ru": "Обман", "zh": "诈骗"}},
            {"arabic": "ظرف", "transliteration": {"en": "Ẓarf", "ar": "ظرف", "fr": "Ẓarf", "de": "Ẓarf", "ru": "зарф", "zh": "扎尔夫"}, "translation": {"en": "Wit / Elegance", "fr": "Esprit", "de": "Witz", "ru": "Остроуميه", "zh": "机智"}},
            {"arabic": "ناقد", "transliteration": {"en": "Nāqid", "ar": "ناقد", "fr": "Nāqid", "de": "Nāqid", "ru": "накид", "zh": "纳基德"}, "translation": {"en": "Critic", "fr": "Critique", "de": "Kritiker", "ru": "Критик", "zh": "评论家"}},
            {"arabic": "نوادر", "transliteration": {"en": "Nawādir", "ar": "نوادر", "fr": "Nawādir", "de": "Nawādir", "ru": "навадир", "zh": "纳瓦迪尔"}, "translation": {"en": "Anecdotes", "fr": "Anecdotes", "de": "Anekdoten", "ru": "Анекдоты", "zh": "轶事"}}
        ],
        "sentences": [
            {"arabic": "تعتبر مقامات الحريري ذروة الأدب التعليمي.", "transliteration": {"en": "Tu'tabaru maqāmāt al-Ḥarīrī dhurwat al-adab at-ta'līmī", "fr": "Tu'tabaru maqāmāt al-Ḥarīrī dhurwat al-adab at-ta'līmī", "de": "Tu'tabaru maqāmāt al-Ḥarīrī dhurwat al-adab at-ta'līmī", "ru": "Тутабару макамат аль-Харири зурват аль-адаб ат-талими", "zh": "哈里里的马卡马特被认为是教育文学的巅峰"}, "translation": {"en": "The maqamat of Al-Hariri are considered the pinnacle of educational literature.", "fr": "Les maqamat d'Al-Hariri sont considérés comme le summum de la littérature éducative.", "de": "Die Maqamat von Al-Hariri gelten als der Höhepunkt der pädagogischen Literatur.", "ru": "Макамат Аль-Харири считаются вершиной дидактической литературы.", "zh": "哈里里的马卡马特被认为是教育文学的巅峰"}},
            {"arabic": "يعتمد فن المقامة على السجع المتكلف.", "transliteration": {"en": "Ya'tamidu fann al-maqāmah 'ala as-saj' al-mutakallaf", "fr": "Ya'tamidu fann al-maqāmah 'ala as-saj' al-mutakallaf", "de": "Ya'tamidu fann al-maqāmah 'ala as-saj' al-mutakallaf", "ru": "Ятамиду фанн аль-макама аля ас-садж аль-мутакаллаф", "zh": "马卡马艺术依赖于矫情的骈文"}, "translation": {"en": "The art of maqamah relies on elaborate rhymed prose.", "fr": "L'art du maqamah repose sur une prose rimée élaborée.", "de": "Die Kunst der Maqamah stützt sich auf kunstvolle Reimprosa.", "ru": "Искусство макама опирается на сложную рифмованную прозу.", "zh": "马卡马艺术依赖于精致的骈文"}},
            {"arabic": "يستخدم البطل ذكاءه للتلاعب بالناس.", "transliteration": {"en": "Yastakhdimu al-baṭal dhakā'ahu lil-talā'ub bin-nās", "fr": "Yastakhdimu al-baṭal dhakā'ahu lil-talā'ub bin-nās", "de": "Yastakhdimu al-baṭal dhakā'ahu lil-talā'ub bin-nās", "ru": "Ястахдиму аль-баталь закаху лит-талаиуб бин-нас", "zh": "英雄利用他的智慧来操纵人们"}, "translation": {"en": "The hero uses his intelligence to manipulate people.", "fr": "Le héros utilise son intelligence pour manipuler les gens.", "de": "Der Held nutzt seine Intelligenz, um Menschen zu manipulieren.", "ru": "Герой использует свой интеллект для манипулирования людьми.", "zh": "英雄利用他的智慧来操纵人们"}},
            {"arabic": "تعكس المقامات الواقع الاجتماعي في العصر العباسي.", "transliteration": {"en": "Ta'kisu al-maqāmāt al-wāqi' al-ijtimā'ī fī al-'aṣr al-'abbāsī", "fr": "Ta'kisu al-maqāmāt al-wāqi' al-ijtimā'ī fī al-'aṣr al-'abbāsī", "de": "Ta'kisu al-maqāmāt al-wāqi' al-ijtimā'ī fī al-'aṣr al-'abbāsī", "ru": "Такису аль-макамат аль-ваки аль-иджтимаи фи аль-аср аль-аббаси", "zh": "马卡马特反映了阿巴斯王朝时期的社会现实"}, "translation": {"en": "The maqamat reflect the social reality of the Abbasid era.", "fr": "Les maqamat reflètent la réalité sociale de l'époque abbasside.", "de": "Die Maqamat spiegeln die soziale Realität der Abbasidenzeit wider.", "ru": "Макамат отражают социальную реальность эпохи Аббасидов.", "zh": "《马卡马特》反映了阿巴斯王朝时期的社会现实"}},
            {"arabic": "يتميز الراوي بقدرة كبيرة على الوصف.", "transliteration": {"en": "Yatamayyazu ar-rāwī biqudrah kabīrah 'ala al-waṣf", "fr": "Yatamayyazu ar-rāwī biqudrah kabīrah 'ala al-waṣf", "de": "Yatamayyazu ar-rāwī biqudrah kabīrah 'ala al-waṣf", "ru": "Ятамайязу ар-рави бикудра кабира аля аль-васф", "zh": "讲故事的人具有很强的描述能力"}, "translation": {"en": "The narrator is characterized by a great ability to describe.", "fr": "Le narrateur se caractérise par une grande capacité de description.", "de": "Der Erzähler zeichnet sich durch eine große Beschreibungsfähigkeit aus.", "ru": "Рассказчик характеризуется большой способностью к описанию.", "zh": "叙述者的特点是具有很强的描写能力"}}
        ]
    },
    "l3": {
         "words": [
            {"arabic": "بلاط", "transliteration": {"en": "Balāṭ", "ar": "بلاط", "fr": "Balāṭ", "de": "Balāṭ", "ru": "балят", "zh": "巴拉特"}, "translation": {"en": "Court (Royal)", "fr": "Cour", "de": "Hof", "ru": "Двор", "zh": "朝廷"}},
            {"arabic": "خلفاء", "transliteration": {"en": "Khulafā'", "ar": "خلفاء", "fr": "Khulafā'", "de": "Khulafā'", "ru": "хулафа", "zh": "库拉法"}, "translation": {"en": "Caliphs", "fr": "Califes", "de": "Kalifen", "ru": "Халифы", "zh": "哈里发"}},
            {"arabic": "مديح", "transliteration": {"en": "Madīḥ", "ar": "مديح", "fr": "Madīḥ", "de": "Madīḥ", "ru": "мадих", "zh": "马迪赫"}, "translation": {"en": "Eulogy / Praise", "fr": "Éloge", "de": "Lobrede", "ru": "Похвала", "zh": "赞美诗"}},
            {"arabic": "هجاء", "transliteration": {"en": "Hijā'", "ar": "هجاء", "fr": "Hijā'", "de": "Hijā'", "ru": "хиджа", "zh": "希贾"}, "translation": {"en": "Satire", "fr": "Satire", "de": "Satire", "ru": "Сатира", "zh": "讽刺"}},
            {"arabic": "رثاء", "transliteration": {"en": "Rithā'", "ar": "رثاء", "fr": "Rithā'", "de": "Rithā'", "ru": "риса", "zh": "里萨"}, "translation": {"en": "Elegy / Lament", "fr": "Élégie", "de": "Elegie", "ru": "Элегия", "zh": "挽歌"}},
            {"arabic": "نديم", "transliteration": {"en": "Nadīm", "ar": "نديم", "fr": "Nadīm", "de": "Nadīm", "ru": "надим", "zh": "纳迪姆"}, "translation": {"en": "Courtly companion", "fr": "Compagnon", "de": "Gefährte", "ru": "Собутыльник", "zh": "清客"}},
            {"arabic": "رعاية", "transliteration": {"en": "Ri'āyah", "ar": "رعاية", "fr": "Ri'āyah", "de": "Ri'āyah", "ru": "риая", "zh": "里阿亚"}, "translation": {"en": "Patronage", "fr": "Patronage", "de": "Schirmherrschaft", "ru": "Покровительство", "zh": "赞助"}},
            {"arabic": "ترف", "transliteration": {"en": "Taraf", "ar": "ترف", "fr": "Taraf", "de": "Taraf", "ru": "тараф", "zh": "塔拉夫"}, "translation": {"en": "Luxury", "fr": "Luxe", "de": "Luxus", "ru": "Роскошь", "zh": "奢侈"}},
            {"arabic": "مجالس", "transliteration": {"en": "Majālis", "ar": "مجالس", "fr": "Majālis", "de": "Majālis", "ru": "маджалис", "zh": "马贾利斯"}, "translation": {"en": "Salons / Councils", "fr": "Salons", "de": "Ratsversammlungen", "ru": "Собрания", "zh": "沙龙"}},
            {"arabic": "سياسة", "transliteration": {"en": "Siyāsah", "ar": "سياسة", "fr": "Siyāsah", "de": "Siyāsah", "ru": "сияса", "zh": "西亚萨"}, "translation": {"en": "Politics", "fr": "Politique", "de": "Politik", "ru": "Полика", "zh": "政治"}}
        ],
        "sentences": [
            {"arabic": "كان الشعر وسيلة للتقرب من البلاط الخليفي.", "transliteration": {"en": "Kāna ash-shi'ru wasīlah lil-taqarruub min al-balāṭ al-khilafī", "fr": "Kāna ash-shi'ru wasīlah lil-taqarruub min al-balāṭ al-khilafī", "de": "Kāna ash-shi'ru wasīlah lil-taqarruub min al-balāṭ al-khilafī", "ru": "Кана аш-ширу васила лит-такарруб мин аль-балят аль-хилафи", "zh": "诗歌曾是亲近哈里发宫廷的一种方式"}, "translation": {"en": "Poetry was a means of getting closer to the caliphate court.", "fr": "La poésie était un moyen de se rapprocher de la cour du califat.", "de": "Poesie war ein Mittel, um dem Kalifenhof näher zu kommen.", "ru": "Поэзия была средством сближения с двором халифата.", "zh": "诗歌是亲近哈里发宫廷的一种手段"}},
            {"arabic": "ازدهر المديح كقيمة اجتماعية وأدبية.", "transliteration": {"en": "Izdahara al-madīḥ ka-qīmah ijtimā'iyyah wa-adabiyyah", "fr": "Izdahara al-madīḥ ka-qīmah ijtimā'iyyah wa-adabiyyah", "de": "Izdahara al-madīḥ ka-qīmah ijtimā'iyyah wa-adabiyyah", "ru": "Издахара аль-мадих ка-кима иджтимаийя ва-адабийя", "zh": "赞美诗作为一种社会和文学价值而繁荣"}, "translation": {"en": "Eulogy flourished as a social and literary value.", "fr": "L'éloge a fleuri comme une valeur sociale et littéraire.", "de": "Die Lobrede blühte als sozialer und literarischer Wert auf.", "ru": "Панегирик процветал как социальная и литературная ценность.", "zh": "赞美作为一种社会和文学价值而繁荣"}},
            {"arabic": "استخدم الشعراء الهجاء لتصفية الحسابات السياسية.", "transliteration": {"en": "Istakhdama ash-shu'arā' al-hijā' li-taṣfiyat al-ḥisābāt as-siyāsiyyah", "fr": "Istakhdama ash-shu'arā' al-hijā' li-taṣfiyat al-ḥisābāt as-siyāsiyyah", "de": "Istakhdama ash-shu'arā' al-hijā' li-taṣfiyat al-ḥisābāt as-siyāsiyyah", "ru": "Ястахдама аш-шуара аль-хиджа ли-тасфият аль-хисабат ас-сиясийя", "zh": "诗人利用讽刺来清算政治账目"}, "translation": {"en": "Poets used satire to settle political scores.", "fr": "Les poètes utilisaient la satire pour régler des comptes politiques.", "de": "Dichter nutzten Satire, um politische Rechnungen zu begleichen.", "ru": "Поэты использовали сатиру для сведения политических счетов.", "zh": "诗人利用讽刺来结算政治账目"}}
        ]
    },
    "l4": {
        "words": [
            {"arabic": "مجاز", "transliteration": {"en": "Majāz", "ar": "مجاز", "fr": "Majāz", "de": "Majāz", "ru": "маджаз", "zh": "玛雅兹"}, "translation": {"en": "Metaphor / Allegory", "fr": "Métaphore", "de": "Metapher", "ru": "Аллегория", "zh": "比喻"}},
            {"arabic": "كناية", "transliteration": {"en": "Kināyah", "ar": "كناية", "fr": "Kināyah", "de": "Kināyah", "ru": "киная", "zh": "基纳亚"}, "translation": {"en": "Metonymy", "fr": "Métonymie", "de": "Metonymie", "ru": "Метонимия", "zh": "转喻"}},
            {"arabic": "خيال", "transliteration": {"en": "Khayāl", "ar": "خيال", "fr": "Khayāl", "de": "Khayāl", "ru": "хаяль", "zh": "哈亚尔"}, "translation": {"en": "Imagination", "fr": "Imagination", "de": "Phantasie", "ru": "Воображение", "zh": "想象力"}},
            {"arabic": "تجسيد", "transliteration": {"en": "Tajsīd", "ar": "تجسيد", "fr": "Tajsīd", "de": "Tajsīd", "ru": "таджсид", "zh": "塔吉德"}, "translation": {"en": "Personification / Embodiment", "fr": "Personnification", "de": "Verkörperung", "ru": "Олицетворение", "zh": "人格化"}},
            {"arabic": "صور", "transliteration": {"en": "Ṣuwar", "ar": "صور", "fr": "Ṣuwar", "de": "Ṣuwar", "ru": "сувар", "zh": "苏瓦尔"}, "translation": {"en": "Images / Imagery", "fr": "Images", "de": "Bilder", "ru": "Образы", "zh": "意象"}},
            {"arabic": "إيقاع", "transliteration": {"en": "Īqā'", "ar": "إيقاع", "fr": "Īqā'", "de": "Īqā'", "ru": "ика", "zh": "伊卡"}, "translation": {"en": "Rhythm", "fr": "Rythme", "de": "Rhythmus", "ru": "Ритм", "zh": "节奏"}},
            {"arabic": "تأويل", "transliteration": {"en": "Ta'wīl", "ar": "تأويل", "fr": "Ta'wīl", "de": "Ta'wīl", "ru": "тавиль", "zh": "塔维勒"}, "translation": {"en": "Interpretation", "fr": "Interprétation", "de": "Interpretation", "ru": "Толкование", "zh": "解读"}},
            {"arabic": "دلالة", "transliteration": {"en": "Dalālah", "ar": "دلالة", "fr": "Dalālah", "de": "Dalālah", "ru": "даляля", "zh": "达拉拉"}, "translation": {"en": "Significance / Indication", "fr": "Signification", "de": "Bedeutung", "ru": "Значение", "zh": "意义"}},
            {"arabic": "رمز", "transliteration": {"en": "Ramz", "ar": "رمز", "fr": "Ramz", "de": "Ramz", "ru": "рамз", "zh": "拉姆兹"}, "translation": {"en": "Symbol", "fr": "Symbole", "de": "Symbol", "ru": "Символ", "zh": "符号"}},
            {"arabic": "بنية", "transliteration": {"en": "Binyah", "ar": "بنية", "fr": "Binyah", "de": "Binyah", "ru": "бинья", "zh": "宾亚"}, "translation": {"en": "Structure", "fr": "Structure", "de": "Struktur", "ru": "Структура", "zh": "结构"}}
        ],
        "sentences": [
            {"arabic": "تعتبر الاستعارة أداة جوهرية في بناء النص الشعري.", "transliteration": {"en": "Tu'tabaru al-isti'ārah adāh jawhariyyah fī binā' an-naṣṣ ash-shi'rī", "fr": "Tu'tabaru al-isti'ārah adāh jawhariyyah fī binā' an-naṣṣ ash-shi'rī", "de": "Tu'tabaru al-isti'ārah adāh jawhariyyah fī binā' an-naṣṣ ash-shi'rī", "ru": "Тутабару аль-истиара ада джавхарийя фи бина ан-насс аш-шири", "zh": "隐喻被认为是构建诗意文本的重要工具"}, "translation": {"en": "Metaphor is considered an essential tool in building the poetic text.", "fr": "La métaphore est considérée comme un outil essentiel dans la construction du texte poétique.", "de": "Die Metapher gilt als wesentliches Instrument beim Aufbau des poetischen Textes.", "ru": "Метафора считается важным инструментом в построении поэтического текста.", "zh": "隐喻被认为是构建诗意文本的重要工具"}},
            {"arabic": "يخلق المجاز أبعاداً دلالية جديدة للكلمات.", "transliteration": {"en": "Yakhluqu al-majāz ab'ādan dalāliyyah jadīdah lil-kalimāt", "fr": "Yakhluqu al-majāz ab'ādan dalāliyyah jadīdah lil-kalimāt", "de": "Yakhluqu al-majāz ab'ādan dalāliyyah jadīdah lil-kalimāt", "ru": "Яхлюку аль-маджаз абадан далялийя джадида лиль-калимат", "zh": "隐喻为词语创造了新的语义维度"}, "translation": {"en": "Metaphor creates new semantic dimensions for words.", "fr": "La métaphore crée de nouvelles dimensions sémantiques pour les mots.", "de": "Metaphern schaffen neue semantische Dimensionen für Wörter.", "ru": "Метафора создает новые семантические измерения для слов.", "zh": "比喻为词语创造了新的语义维度"}},
            {"arabic": "بنية القصيدة تعتمد على تداخل الصور والرموز.", "transliteration": {"en": "Binyat al-qaṣīdah ta'tamidu 'ala tadākhul aṣ-ṣuwar war-rumūz", "fr": "Binyat al-qaṣīdah ta'tamidu 'ala tadākhul aṣ-ṣuwar war-rumūz", "de": "Binyat al-qaṣīdah ta'tamidu 'ala tadākhul aṣ-ṣuwar war-rumūz", "ru": "Биньят аль-касида татамиду аля тадахуль ас-сувар вар-румуз", "zh": "诗歌的结构依赖于意象和符号的交叉"}, "translation": {"en": "The structure of the poem depends on the overlapping of images and symbols.", "fr": "La structure du poème dépend du chevauchement des images et des symboles.", "de": "Die Structure des Gedichts hängt von der Überschneidung von Bildern und Symbolen ab.", "ru": "Структура стихотворения зависит от переплетения образов и символов.", "zh": "诗歌的结构依赖于意象与符号的交叠"}}
        ]
    },
    "l5": {
        "words": [
            {"arabic": "نقد", "transliteration": {"en": "Naqd", "ar": "نقد", "fr": "Naqd", "de": "Naqd", "ru": "накд", "zh": "纳克德"}, "translation": {"en": "Criticism", "fr": "Critique", "de": "Kritik", "ru": "Критика", "zh": "批评"}},
            {"arabic": "بيان", "transliteration": {"en": "Bayān", "ar": "بيان", "fr": "Bayān", "de": "Bayān", "ru": "баян", "zh": "巴扬"}, "translation": {"en": "Clarity / Proclamation", "fr": "Clarté", "de": "Klarheit", "ru": "Ясность", "zh": "表述"}},
            {"arabic": "تبيين", "transliteration": {"en": "Tabyīn", "ar": "تبيين", "fr": "Tabyīn", "de": "Tabyīn", "ru": "تبييين", "zh": "塔宾"}, "translation": {"en": "Clarification / Elucidation", "fr": "Clarification", "de": "Klärung", "ru": "Разъяснение", "zh": "阐释"}},
            {"arabic": "مخلوقات", "transliteration": {"en": "Makhlūqāt", "ar": "مخلوقات", "fr": "Makhlūqāt", "de": "Makhlūqāt", "ru": "махлюкат", "zh": "马克卢卡特"}, "translation": {"en": "Creatures", "fr": "Créatures", "de": "Kreaturen", "ru": "Существа", "zh": "生物"}},
            {"arabic": "نوادر", "transliteration": {"en": "Nawādir", "ar": "نوادر", "fr": "Nawādir", "de": "Nawādir", "ru": "навадир", "zh": "纳瓦迪尔"}, "translation": {"en": "Anecdotes", "fr": "Anecdotes", "de": "Anekdoten", "ru": "Анекдоты", "zh": "轶事"}},
            {"arabic": "أدب", "transliteration": {"en": "Adab", "ar": "أدب", "fr": "Adab", "de": "Adab", "ru": "адаб", "zh": "阿达布"}, "translation": {"en": "Literature / Manners", "fr": "Littérature", "de": "Literatur", "ru": "Литература", "zh": "文学"}},
            {"arabic": "فطنة", "transliteration": {"en": "Fiṭnah", "ar": "فطنة", "fr": "Fiṭnah", "de": "Fiṭnah", "ru": "фитна", "zh": "菲特纳"}, "translation": {"en": "Sagacity / Intelligence", "fr": "Sagacité", "de": "Scharfsinn", "ru": "Проницательность", "zh": "睿智"}},
            {"arabic": "رسائل", "transliteration": {"en": "Rasā'il", "ar": "رسائل", "fr": "Rasā'il", "de": "Rasā'il", "ru": "расаиль", "zh": "拉赛尔"}, "translation": {"en": "Letters / Treatises", "fr": "Lettres", "de": "Briefe", "ru": "Письма", "zh": "信件"}},
            {"arabic": "مجتمع", "transliteration": {"en": "Mujtama'", "ar": "مجتمع", "fr": "Mujtama'", "de": "Mujtama'", "ru": "муджтама", "zh": "穆贾塔马"}, "translation": {"en": "Society", "fr": "Société", "de": "Gesellschaft", "ru": "Общество", "zh": "社会"}},
            {"arabic": "تأمل", "transliteration": {"en": "Ta'ammul", "ar": "تأمل", "fr": "Ta'ammul", "de": "Ta'ammul", "ru": "тааммуль", "zh": "塔阿穆尔"}, "translation": {"en": "Contemplation", "fr": "Contemplation", "de": "Kontemplation", "ru": "Созерцание", "zh": "沉思"}}
        ],
        "sentences": [
            {"arabic": "يجمع الجاحظ بين العلم والترفيه في كُتبه.", "transliteration": {"en": "Yajma'u al-Jāḥiẓ bayna al-'ilm wal-tarfīh fī kutubih", "fr": "Yajma'u al-Jāḥiẓ bayna al-'ilm wal-tarfīh fī kutubih", "de": "Yajma'u al-Jāḥiẓ bayna al-'ilm wal-tarfīh fī kutubih", "ru": "Яджмау аль-Джахиза байна аль-ильм ват-тарфих фи кутубих", "zh": "贾希兹在他的书中结合了科学和娱乐"}, "translation": {"en": "Al-Jahiz combines science and entertainment in his books.", "fr": "Al-Jahiz allie science et divertissement dans ses livres.", "de": "Al-Jahiz verbindet in seinen Büchern Wissenschaft und Unterhaltung.", "ru": "Аль-Джахис сочетает в своих книгах науку и развлечение.", "zh": "贾希兹在他的著作中融合了科学与娱乐"}},
            {"arabic": "كتاب البيان والتبيين أساس في علم البلاغة.", "transliteration": {"en": "Kitāb al-Bayān wal-Tabyīn asās fī 'ilm al-balāghah", "fr": "Kitāb al-Bayān wal-Tabyīn asās fī 'ilm al-balāghah", "de": "Kitāb al-Bayān wal-Tabyīn asās fī 'ilm al-balāghah", "ru": "Китаб аль-Баян ват-Табиин асас фи ильм аль-балага", "zh": "《澄清与解释》是修辞学的基础"}, "translation": {"en": "The book 'Al-Bayan wa Al-Tabyin' is a foundation in the science of rhetoric.", "fr": "Le livre 'Al-Bayan wa Al-Tabyin' est une base dans la science de la rhétorique.", "de": "Das Buch 'Al-Bayan wa Al-Tabyin' ist eine Grundlage der Rhetorik.", "ru": "Книга «Аль-Баян ва ат-Табиин» является основой науки о риторике.", "zh": "《澄清与说明》是修辞学的基础"}},
            {"arabic": "تمتاز رسائل الجاحظ بأسلوب النقد الاجتماعي الساخر.", "transliteration": {"en": "Tamtāzu rasā'il al-Jāḥiẓ bi-uslūb an-naqd al-ijtimā'ī as-sākhir", "fr": "Tamtāzu rasā'il al-Jāḥiẓ bi-uslūb an-naqd al-ijtimā'ī as-sākhir", "de": "Tamtāzu rasā'il al-Jāḥiẓ bi-uslūb an-naqd al-ijtimā'ī as-sākhir", "ru": "Тамтазу расаиль аль-Джахиза би-услюб ан-накд аль-иджтимаи ас-сахир", "zh": "贾希兹的信件以讽刺社会批评的风格为特征"}, "translation": {"en": "Al-Jahiz's letters are characterized by a style of satirical social criticism.", "fr": "Les lettres d'Al-Jahiz se caractérisent par un style de critique sociale satirique.", "de": "Die Briefe von Al-Jahiz zeichnen sich durch einen satirischen sozialkritischen Stil aus.", "ru": "Письма Аль-Джахиза характеризуются сатирическим стилем социальной критики.", "zh": "贾希兹的信札具有讽刺性社会批判的风格"}}
        ]
    },
    "l6": {
        "words": [
            {"arabic": "موشحات", "transliteration": {"en": "Muwashshaḥāt", "ar": "موشحات", "fr": "Muwashshaḥāt", "de": "Muwashshaḥāt", "ru": "мувашшахат", "zh": "穆瓦沙哈特"}, "translation": {"en": "Muwashshahat (Andalusian poems)", "fr": "Muwashshahat", "de": "Muwashshahat", "ru": "Мувашшахат", "zh": "穆瓦沙哈特"}},
            {"arabic": "أغراض", "transliteration": {"en": "Aghrāḍ", "ar": "أغراض", "fr": "Aghrāḍ", "de": "Aghrāḍ", "ru": "аград", "zh": "阿格拉德"}, "translation": {"en": "Purposes / Themes", "fr": "Thèmes", "de": "Zwecke / Themen", "ru": "Цели / Темы", "zh": "目的/主题"}},
            {"arabic": "أدوار", "transliteration": {"en": "Adwār", "ar": "أدوار", "fr": "Adwār", "de": "Adwār", "ru": "адвар", "zh": "阿德瓦尔"}, "translation": {"en": "Roles / Rounds", "fr": "Rôles", "de": "Rollen / Runden", "ru": "Роли / Раунды", "zh": "角色/轮次"}},
            {"arabic": "موسيقى", "transliteration": {"en": "Mūsīqā", "ar": "موسيقى", "fr": "Mūsīqā", "de": "Mūsīqā", "ru": "музыка", "zh": "音乐"}, "translation": {"en": "Music", "fr": "Musique", "de": "Musik", "ru": "Музыка", "zh": "音乐"}},
            {"arabic": "تنوع", "transliteration": {"en": "Tanawwu'", "ar": "تنوع", "fr": "Tanawwu'", "de": "Tanawwu'", "ru": "танавву", "zh": "塔纳乌"}, "translation": {"en": "Diversity / Variation", "fr": "Diversité", "de": "Vielfalt", "ru": "Разнообразие", "zh": "多样性"}},
            {"arabic": "تراث", "transliteration": {"en": "Turāth", "ar": "تراث", "fr": "Turāth", "de": "Turāth", "ru": "турас", "zh": "图拉斯"}, "translation": {"en": "Heritage", "fr": "Patrimoine", "de": "Erbe", "ru": "Наследие", "zh": "遗产"}},
            {"arabic": "قفل", "transliteration": {"en": "Qufl", "ar": "قفل", "fr": "Qufl", "de": "Qufl", "ru": "куфль", "zh": "库夫尔"}, "translation": {"en": "Refrain / Closure", "fr": "Refrain", "de": "Refrain", "ru": "Припев / Концовка", "zh": "叠句"}},
            {"arabic": "خرجة", "transliteration": {"en": "Kharjah", "ar": "خرجة", "fr": "Kharjah", "de": "Kharjah", "ru": "харджа", "zh": "哈尔贾"}, "translation": {"en": "Exit / Final couplet", "fr": "Sortie", "de": "Abschluss", "ru": "Харджа (финальное двустишие)", "zh": "结尾句"}},
            {"arabic": "طبيعة", "transliteration": {"en": "Ṭabī'ah", "ar": "طبيعة", "fr": "Ṭabī'ah", "de": "Ṭabī'ah", "ru": "табиа", "zh": "塔比亚"}, "translation": {"en": "Nature", "fr": "Nature", "de": "Natur", "ru": "Природа", "zh": "自然"}},
            {"arabic": "حب", "transliteration": {"en": "Ḥubb", "ar": "حب", "fr": "Ḥubb", "de": "Ḥubb", "ru": "хуبб", "zh": "胡布"}, "translation": {"en": "Love", "fr": "Amour", "de": "Liebe", "ru": "Любовь", "zh": "爱"}}
        ],
        "sentences": [
            {"arabic": "ظهرت الموشحات كنوع شعري جديد في الأندلس.", "transliteration": {"en": "Ẓaharat al-muwashshaḥāt ka-naw' shi'rī jadīd fī al-Andalus", "fr": "Ẓaharat al-muwashshaḥāt ka-naw' shi'rī jadīd fī al-Andalus", "de": "Ẓaharat al-muwashshaḥāt ka-naw' shi'rī jadīd fī al-Andalus", "ru": "Захарат аль-мувашшахат ка-нав шири джадид фи аль-Андалус", "zh": "穆瓦沙哈特作为一种新的诗歌类型出现在安达卢西亚"}, "translation": {"en": "Muwashshahat appeared as a new poetic genre in Andalusia.", "fr": "Les muwashshahat sont apparus comme un nouveau genre poétique en Andalousie.", "de": "Muwashshahat entstanden als neues Gedichtgenre in Andalusien.", "ru": "Мувашшахат появились как новый поэтический жанр в Андалусии.", "zh": "穆瓦沙哈特在安达卢西亚作为一种新的诗歌流派出现"}},
            {"arabic": "تتميز الموشحات بتعدد القوافي والأوزان.", "transliteration": {"en": "Tatamayyazu al-muwashshaḥāt bi-ta'addud al-qawāfī wal-awzān", "fr": "Tatamayyazu al-muwashshaḥāt bi-ta'addud al-qawāfī wal-awzān", "de": "Tatamayyazu al-muwashshaḥāt bi-ta'addud al-qawāfī wal-awzān", "ru": "Татамайязу аль-мувашшахат би-тааддуд аль-кавафи валь-авзан", "zh": "穆瓦沙哈特的特点是多种韵律和重量"}, "translation": {"en": "Muwashshahat are characterized by multiple rhymes and meters.", "fr": "Les muwashshahat se caractérisent par des rimes et des mètres multiples.", "de": "Muwashshahat zeichnen sich durch vielfältige Reime und Metren aus.", "ru": "Мувашшахат характеризуются множественностью рифм и размеров.", "zh": "穆瓦沙哈特的特点是韵律和格律的多样性"}},
            {"arabic": "الخرجة هي الجزء الأخير والأهم في الموشح.", "transliteration": {"en": "Al-kharjah hiya al-juz' al-akhīr wal-aham fī al-muwashshaḥ", "fr": "Al-kharjah hiya al-juz' al-akhīr wal-aham fī al-muwashshaḥ", "de": "Al-kharjah hiya al-juz' al-akhīr wal-aham fī al-muwashshaḥ", "ru": "Аль-харджа хия аль-джуз аль-ахир валь-ахамм фи аль-мувашшах", "zh": "结尾句是穆瓦沙哈特最后也是最重要的部分"}, "translation": {"en": "The Kharjah is the last and most important part of the Muwashshah.", "fr": "La Kharjah est la dernière et la plus importante partie du Muwashshah.", "de": "Die Kharjah ist der letzte und wichtigste Teil des Muwashshah.", "ru": "Харджа — это последняя и самая важная часть мувашшаха.", "zh": "哈尔贾是穆瓦沙哈特最重要也是最后一部分"}}
        ]
    },
    "l7": {
        "words": [
            {"arabic": "مصطلحات", "transliteration": {"en": "Muṣṭalaḥāt", "ar": "مصطلحات", "fr": "Muṣṭalaḥāt", "de": "Muṣṭalaḥāt", "ru": "мусталахат", "zh": "穆斯塔拉哈特"}, "translation": {"en": "Terminology", "fr": "Terminologie", "de": "Terminologie", "ru": "Терминология", "zh": "术语"}},
            {"arabic": "مراجعة", "transliteration": {"en": "Murāja'ah", "ar": "مراجعة", "fr": "Murāja'ah", "de": "Murāja'ah", "ru": "мураджаа", "zh": "穆拉贾"}, "translation": {"en": "Review", "fr": "Révision", "de": "Überprüfung", "ru": "Обзор", "zh": "复习"}},
            {"arabic": "أصالة", "transliteration": {"en": "Aṣālah", "ar": "أصالة", "fr": "Aṣālah", "de": "Aṣālah", "ru": "асаля", "zh": "阿萨拉"}, "translation": {"en": "Authenticity", "fr": "Authenticité", "de": "Authentizität", "ru": "Подлинность", "zh": "正统性"}},
            {"arabic": "معاصر", "transliteration": {"en": "Mu'āṣir", "ar": "معاصر", "fr": "Mu'āṣir", "de": "Mu'āṣir", "ru": "муасир", "zh": "穆阿西尔"}, "translation": {"en": "Contemporary", "fr": "Contemporain", "de": "Zeitgenössisch", "ru": "Современный", "zh": "当代"}},
            {"arabic": "تطور", "transliteration": {"en": "Taṭawwur", "ar": "تطور", "fr": "Taṭawwur", "de": "Taṭawwur", "ru": "татаввур", "zh": "塔塔武尔"}, "translation": {"en": "Development", "fr": "Développement", "de": "Entwicklung", "ru": "Развитие", "zh": "发展"}},
            {"arabic": "موهبة", "transliteration": {"en": "Mawhibah", "ar": "موهبة", "fr": "Mawhibah", "de": "Mawhibah", "ru": "мавхиба", "zh": "莫希巴"}, "translation": {"en": "Talent", "fr": "Talent", "de": "Talent", "ru": "Талант", "zh": "天赋"}},
            {"arabic": "ثقافة", "transliteration": {"en": "Thaqāfah", "ar": "ثقافة", "fr": "Thaqāfah", "de": "Thaqāfah", "ru": "сакафа", "zh": "萨卡法"}, "translation": {"en": "Culture", "fr": "Culture", "de": "Kultur", "ru": "Культура", "zh": "文化"}},
            {"arabic": "تقييم", "transliteration": {"en": "Taqyīm", "ar": "تقييم", "fr": "Taqyīm", "de": "Taqyīm", "ru": "такийم", "zh": "塔基姆"}, "translation": {"en": "Evaluation", "fr": "Évaluation", "de": "Bewertung", "ru": "Оценка", "zh": "评估"}},
            {"arabic": "مهارة", "transliteration": {"en": "Mahārah", "ar": "مهارة", "fr": "Mahārah", "de": "Mahārah", "ru": "махара", "zh": "马哈拉"}, "translation": {"en": "Skill", "fr": "Compétence", "de": "Fähigkeit", "ru": "Навык", "zh": "技能"}},
            {"arabic": "أسلوب", "transliteration": {"en": "Uslūb", "ar": "أسلوب", "fr": "Uslūb", "de": "Uslūb", "ru": "услюб", "zh": "乌斯鲁布"}, "translation": {"en": "Style", "fr": "Style", "de": "Stil", "ru": "Стиль", "zh": "风格"}}
        ],
        "sentences": [
            {"arabic": "تساعد المراجعة الدورية على ترسيخ المصطلحات الأدبية.", "transliteration": {"en": "Tusā'idu al-murāja'ah ad-dawriyyah 'ala tarsīkh al-muṣṭalaḥāt al-adabiyyah", "fr": "Tusā'idu al-murāja'ah ad-dawriyyah 'ala tarsīkh al-muṣṭalaḥāt al-adabiyyah", "de": "Tusā'idu al-murāja'ah ad-dawriyyah 'ala tarsīkh al-muṣṭalaḥāt al-adabiyyah", "ru": "Тусаиду аль-мураджаа ад-даврийя аля тарсих аль-мусталахат аль-адабийя", "zh": "定期复习有助于巩固文学术语"}, "translation": {"en": "Regular review helps to consolidate literary terminology.", "fr": "Une révision régulière aide à consolider la terminologie littéraire.", "de": "Regelmäßige Überprüfung hilft, literarische Begriffe zu festigen.", "ru": "Регулярный обзор помогает закрепить литературную терминологию.", "zh": "定期复习有助于巩固文学术语"}},
            {"arabic": "نحتاج إلى تقييم شامل لمهاراتنا في النقد الأدبي.", "transliteration": {"en": "Naḥtāju ila taqyīm shāmil li-mahārātinā fī an-naqd al-adabī", "fr": "Naḥtāju ila taqyīm shāmil li-mahārātinā fī an-naqd al-adabī", "de": "Naḥtāju ila taqyīm shāmil li-mahārātinā fī an-naqd al-adabī", "ru": "Нахтаджу иля такийм шамиль ли-махаратина фи ан-накд аль-адаби", "zh": "我们需要对我们的文学批评技能进行全面评估"}, "translation": {"en": "We need a comprehensive evaluation of our literary criticism skills.", "fr": "Nous avons besoin d'une évaluation complète de nos compétences en critique littéraire.", "de": "Wir brauchen eine umfassende Bewertung unserer Fähigkeiten in der Literaturkritik.", "ru": "Нам нужна всесторонняя оценка наших навыков литературной критики.", "zh": "我们需要对我们的文学批评技能进行全面评估"}},
            {"arabic": "تطور الأسلوب الأدبي عبر العصور المختلفة.", "transliteration": {"en": "Taṭawwara al-uslūb al-adabī 'abra al-'uṣūr al-mukhtalifah", "fr": "Taṭawwara al-uslūb al-adabī 'abra al-'uṣūr al-mukhtalifah", "de": "Taṭawwara al-uslūb al-adabī 'abra al-'uṣūr al-mukhtalifah", "ru": "Татаввара аль-услюб аль-адаби абра аль-усур аль-мухталифа", "zh": "文学风格随着时代的变迁而不断发展"}, "translation": {"en": "The literary style developed across different eras.", "fr": "Le style littéraire s'est développé à travers différentes époques.", "de": "Der literarische Stil entwickelte sich über verschiedene Epochen hinweg.", "ru": "Литературный стиль развивался на протяжении различных эпох.", "zh": "文学风格在不同的时代背景下得到了发展"}}
        ]
    },
    "l8": {
        "words": [
            {"arabic": "نظم", "transliteration": {"en": "Naẓm", "ar": "نظم", "fr": "Naẓm", "de": "Naẓm", "ru": "наズム", "zh": "纳兹姆"}, "translation": {"en": "Composition (of poetry)", "fr": "Composition", "de": "Komposition", "ru": "Сложение (стихов)", "zh": "构思"}},
            {"arabic": "بيتين", "transliteration": {"en": "Baytayn", "ar": "بيتين", "fr": "Baytayn", "de": "Baytayn", "ru": "байтайн", "zh": "拜泰恩"}, "translation": {"en": "Two verses", "fr": "Deux vers", "de": "Zwei Verse", "ru": "Два стиха", "zh": "两行诗"}},
            {"arabic": "عروض", "transliteration": {"en": "Arūḍ", "ar": "عروض", "fr": "Arūḍ", "de": "Arūḍ", "ru": "аруд", "zh": "阿鲁德"}, "translation": {"en": "Prosody", "fr": "Prosodie", "de": "Metrik", "ru": "Просодия", "zh": "格律"}},
            {"arabic": "بحر", "transliteration": {"en": "Baḥr", "ar": "بحر", "fr": "Baḥr", "de": "Baḥr", "ru": "бахр", "zh": "巴哈尔"}, "translation": {"en": "Poetic meter", "fr": "Mètre poétique", "de": "Versmaß", "ru": "Поэтический размер", "zh": "诗律"}},
            {"arabic": "تفعيلة", "transliteration": {"en": "Taf'īlah", "ar": "تفعيلة", "fr": "Taf'īlah", "de": "Taf'īlah", "ru": "тафиля", "zh": "塔菲拉"}, "translation": {"en": "Metrical foot", "fr": "Pied métrique", "de": "Metrischer Fuß", "ru": "Стопа (в стихе)", "zh": "音步"}},
            {"arabic": "إلهام", "transliteration": {"en": "Ilhām", "ar": "إلهام", "fr": "Ilhām", "de": "Ilhām", "ru": "ильхам", "zh": "伊尔哈姆"}, "translation": {"en": "Inspiration", "fr": "Inspiration", "de": "Inspiration", "ru": "Вдохновение", "zh": "灵感"}},
            {"arabic": "قريحة", "transliteration": {"en": "Qarīḥah", "ar": "قريحة", "fr": "Qarīḥah", "de": "Qarīḥah", "ru": "кариха", "zh": "卡里哈"}, "translation": {"en": "Innate talent / Wit", "fr": "Talent inné", "de": "Angeborenes Talent", "ru": "Природный талант", "zh": "天赋"}},
            {"arabic": "إبداع", "transliteration": {"en": "Ibdā'", "ar": "إبداع", "fr": "Ibdā'", "de": "Ibdā'", "ru": "ибدا", "zh": "伊布达"}, "translation": {"en": "Creativity", "fr": "Créativité", "de": "Kreativität", "ru": "Творчество", "zh": "创造力"}},
            {"arabic": "صياغة", "transliteration": {"en": "Ṣiyāghah", "ar": "صياغة", "fr": "Ṣiyāghah", "de": "Ṣiyāghah", "ru": "сияга", "zh": "西亚加"}, "translation": {"en": "Drafting / Formulation", "fr": "Formulation", "de": "Formulierung", "ru": "Формулировка", "zh": "起草"}},
            {"arabic": "تجربة", "transliteration": {"en": "Tajribah", "ar": "تجربة", "fr": "Tajribah", "de": "Tajribah", "ru": "таджриба", "zh": "塔吉巴"}, "translation": {"en": "Experience", "fr": "Expérience", "de": "Erfahrung", "ru": "Опыт", "zh": "经验"}}
        ],
        "sentences": [
            {"arabic": "يتطلب نظم الشعر معرفة عميقة بقواعد العروض.", "transliteration": {"en": "Yataṭallabu naẓm ash-shi'r ma'rifah 'amīqah bi-qawā'id al-'arūḍ", "fr": "Yataṭallabu naẓm ash-shi'r ma'rifah 'amīqah bi-qawā'id al-'arūḍ", "de": "Yataṭallabu naẓm ash-shi'r ma'rifah 'amīqah bi-qawā'id al-'arūḍ", "ru": "Ятаталлябу назм аш-шир марифа амика би-каваид аль-аруд", "zh": "诗歌创作需要对格律规则有深刻的了解"}, "translation": {"en": "Composing poetry requires a deep knowledge of the rules of prosody.", "fr": "Composer de la poésie nécessite une connaissance approfondie des règles de la prosodie.", "de": "Das Dichten erfordert tiefe Kenntnisse der Metrikregeln.", "ru": "Сложение стихов требует глубоких знаний правил просодии.", "zh": "诗歌创作需要对格律规则有深入的了解"}},
            {"arabic": "استخدم قريحتك لابتكار صور شعرية فريدة.", "transliteration": {"en": "Istakhdim qarīḥataka li-ibtikār ṣuwar shi'riyyah farīdah", "fr": "Istakhdim qarīḥataka li-ibtikār ṣuwar shi'riyyah farīdah", "de": "Istakhdim qarīḥataka li-ibtikār ṣuwar shi'riyyah farīdah", "ru": "Ястахдим карихатака ли-ибтикар сувар ширийя фарида", "zh": "利用你的才华创造独特的诗意意象"}, "translation": {"en": "Use your innate talent to create unique poetic images.", "fr": "Utilisez votre talent inné pour créer des images poétiques uniques.", "de": "Nutzen Sie Ihr angeborenes Talent, um einzigartige poetische Bilder zu schaffen.", "ru": "Используйте свой природный талант для создания уникальных поэтических образов.", "zh": "运用你的天赋去创造独特的诗意意象"}},
            {"arabic": "الصياغة الجيدة تعطي القصيدة قوة وتأثيراً.", "transliteration": {"en": "Aṣ-ṣiyāghah al-jayyidah tu'ṭī al-qaṣīdah quwwah wa-ta'thīran", "fr": "Aṣ-ṣiyāghah al-jayyidah tu'ṭī al-qaṣīdah quwwah wa-ta'thīran", "de": "Aṣ-ṣiyāghah al-jayyidah tu'ṭī al-qaṣīdah quwwah wa-ta'thīran", "ru": "Ас-сияга аль-джаййида тути аль-касида кувва ва-тасиран", "zh": "好的构思赋予诗歌力量和影响"}, "translation": {"en": "Good wording gives the poem strength and impact.", "fr": "Une bonne formulation donne au poème force et impact.", "de": "Eine gute Formulierung verleiht dem Gedicht Kraft und Wirkung.", "ru": "Хорошая формулировка придает стихотворению силу и воздействие.", "zh": "良好的措辞赋予诗歌力量和感染力"}}
        ]
    }
}

# Update content_data
for l_id, content in u1_lessons.items():
    if "c1" not in content_data:
        content_data["c1"] = {"u1": {}}
    if "u1" not in content_data["c1"]:
        content_data["c1"]["u1"] = {}
    content_data["c1"]["u1"][l_id] = content

with open('c1_content_data.json', 'w', encoding='utf-8') as f:
    json.dump(content_data, f, ensure_ascii=False, indent=4)
